<?php
/**
 * @file
 * Force material status and material details be shown on object page.
 */

/**
 * Implements hook_entity_view().
 */
function easyddb_materials_display_entity_view($entity, $type, $view_mode, $langcode) {
  // Force material details and status field groups be expanded by default.
  if (isset($entity->content['#groups']['group_material_details']->format_settings)) {
    $entity->content['#groups']['group_material_details']->format_settings['formatter'] = 'open';
  }

  if (isset($entity->content['#groups']['group_holdings_available']->format_settings)) {
    $entity->content['#groups']['group_holdings_available']->format_settings['formatter'] = 'open';
  }
}
